Added cvs-dist target

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,4 +1,4 @@
-## $Id: Makefile.am,v 1.9 1999/04/26 22:41:54 sbooth Exp $
+## $Id: Makefile.am,v 1.10 1999/05/13 17:00:52 sbooth Exp $
 
 if DEMOS
 DEMO = demo
@@ -17,3 +17,33 @@ dist-hook:
 	cp -p $(srcdir)/example/README $(distdir)/example
 	cp -p $(srcdir)/example/Makefile.in $(distdir)/example
 	cp -p $(srcdir)/example/yourSource.cc $(distdir)/example
+
+################################################################
+##
+## Everything past here is useful to the maintainer, but probably not
+## to anybody else (borrowed from libtool/Makefile.am).
+##
+
+## set it to `:' to avoid CVS operations
+CVS = cvs
+
+## Tag before making distribution.  Also, don't make a distribution if
+## checks fail.  Also, make sure the NEWS file is up-to-date.
+cvs-dist: distcheck
+	@if sed '1,2d;3q' $(srcdir)/NEWS | grep -e "$(VERSION)" > /dev/null; then :; else \
+	  echo "NEWS not updated; not releasing" 1>&2; \
+	  exit 1;				\
+	fi
+	cd $(srcdir) && \
+	 $(CVS) -q tag `echo "release-$(VERSION)" | sed 's/\./-/g'`
+	$(MAKE) dist
+
+cvs-diff:
+	thisver=`echo "release-$(VERSION)" | sed 's/\./-/g'`; \
+	if test -z "$$OLDVERSION"; then \
+	  prevno=`echo "$(VERSION)" - 0.01 | bc | sed 's/^\./0./'`; \
+	else prevno="$$OLDVERSION"; fi; \
+	prevver=release-`echo $$prevno | sed 's/\./-/g'`; \
+	$(CVS) -f rdiff -c -r $$prevver -r $$thisver $(PACKAGE) \
+	    > $(PACKAGE)-$$prevno-$(VERSION).diff
+
